apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: integrations
spec:
  schedule: "*/1 * * * *"   # every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "Hello World from CronJob!"
          restartPolicy: OnFailure
