apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: integrations
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox:latest
        command: ["echo", "hello world"]
      restartPolicy: Never
  backoffLimit: 2   # retries if it fails
